openapi: 3.0.0
info:
  title: Authentication API
  description: API for user authentication and profile management
  version: 1.0.0
servers:
  - url: https://api.physical-ai-humanoid-book.com
    description: Production server
  - url: http://localhost:8000
    description: Development server
paths:
  /auth/register:
    post:
      summary: Register a new user
      description: Creates a new user account with background questionnaire
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - name
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address
                password:
                  type: string
                  format: password
                  description: User's password
                name:
                  type: string
                  description: User's display name
                background:
                  type: object
                  description: User background questionnaire responses
                  properties:
                    programmingExperience:
                      type: string
                      enum: [beginner, intermediate, advanced]
                    roboticsExperience:
                      type: string
                      enum: [none, basic, intermediate, advanced]
                    mathBackground:
                      type: string
                      enum: [basic, intermediate, advanced]
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                  token:
                    type: string
                    description: Authentication token
        '400':
          description: Invalid input
        '409':
          description: Email already exists
  /auth/login:
    post:
      summary: Login user
      description: Authenticates user and returns token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                  token:
                    type: string
        '401':
          description: Invalid credentials
  /auth/profile:
    get:
      summary: Get user profile
      description: Retrieve current user's profile information
      security:
        - BearerAuth: []
      responses:
        '200':
          description: User profile retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized
    put:
      summary: Update user profile
      description: Update current user's profile information
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                background:
                  type: object
      responses:
        '200':
          description: Profile updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /auth/preferences:
    put:
      summary: Update user preferences
      description: Update personalization preferences
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                preferences:
                  type: object
                  description: Personalization settings
      responses:
        '200':
          description: Preferences updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
          format: email
        name:
          type: string
        background:
          type: object
        preferences:
          type: object
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT